#! /usr/bin/env bash

if [ ! $1 ] ; then
  echo "Please specify a name for this instance, version and optionally include 'sapi' if this is a sapi instance."
  exit
fi
# Figure out which solr instance to copy
BASEPATH=/opt/solr/solrbase-7/
if [ -n "$3" ] ; then
  if [ $3 = 'sapi' ] ; then
    BASEPATH=/opt/solr/sapi-solrbase-7/
  else
    echo "Unsupported sapi version"
    exit 1
  fi
fi
cp -r "$BASEPATH" /opt/solr/solr-$1

CONTEXT=$"<Context docBase=\"/opt/solr/solr-$1/solr.war\" debug=\"0\" crossContext=\"true\" >
   <Environment name=\"solr/home\" type=\"java.lang.String\" value=\"/opt/solr/solr-$1\" override=\"true\" />
</Context>"
echo "$CONTEXT">"/etc/tomcat6/Catalina/localhost/solr-$1.xml"
chmod g+xw /opt/solr/solr-$1
chown -R :tomcat6 /opt/solr/solr-$1
chmod -R g+w /opt/solr/solr-$1
sudo /etc/init.d/tomcat6 restart
echo "A solr instance has been created and can be visited on this server at http://localhost:8080/solr-$1"
