---
- hosts: all
  remote_user: root
  sudo: yes

  vars_files:
      - config.yml

  roles:
    #- { role: geerlingguy.firewall, tags: ['firewall'] }
    #- { role: geerlingguy.varnish, tags: ['varnish'] }
    #- { role: geerlingguy.tomcat6, tags: ['solr'] }
    #- { role: geerlingguy.solr, tags: ['solr'] }

    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.memcached, tags: ['memcached'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.php-memcached, tags: ['php'] }
    - { role: geerlingguy.php-xdebug, tags: ['php'] }
    - { role: geerlingguy.php-xhprof, tags: ['php'] }
    - { role: geerlingguy.phpmyadmin, tags: ['phpmyadmin'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.daemonize, tags: ['mail'] }
    - { role: geerlingguy.mailhog, tags: ['mail'] }
    - { role: ANXS.nodejs, tags: ['nodejs'] }
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
    - { role: nucivic }
    - { role: nucivic-vim }
    - { role: nucivic-solr }
