---

  - name: Add vimrc.
    template: 
      src=vimrc
      dest=/home/{{ webadmin_user }}/.vimrc owner={{ webadmin_user }} group={{ webadmin_user }}
      
  - name: Clone Drupal vim from Drupal.
    git: >
      repo=http://git.drupal.org/project/vimrc.git
      dest=/home/{{ webadmin_user }}/.drush/vimrc
    
  - name: Creates .vim dir 
    file: path=/home/{{ webadmin_user }}/.vim state=directory owner={{ webadmin_user }} group={{ webadmin_user }}
    
  - name: Creates .vim/autoload dir 
    file: path=/home/{{ webadmin_user }}/.vim/autoload state=directory owner={{ webadmin_user }} group={{ webadmin_user }}
    
  - name: Creates .vim/bundle dir 
    file: path=/home/{{ webadmin_user }}/.vim/bundle state=directory owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Get Pathogen.
    get_url:
      url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
      dest=/home/{{ webadmin_user }}/.vim/autoload/pathogen.vim owner={{ webadmin_user }} group={{ webadmin_user }} mode=0440

  - name: Clone vim setitings from Github.
    git: >
      repo=https://github.com/acouch/vim-drupal.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/drupal-vim
    
  - name: Clone nerdtree from Github.
    git: >
      repo=https://github.com/scrooloose/nerdtree.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/nerdtree    

  - name: Clone fugative from Github.
    git: >
      repo=https://github.com/tpope/vim-fugitive.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/fugative
    
  - name: Clone syntastic from Github.
    git: >
      repo=https://github.com/scrooloose/syntastic.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/syntastic

  - name: Clone snipmate from Github.
    git: >
      repo=https://github.com/msanders/snipmate.vim.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/snipmate

  - name: Clone tagbar from Github.
    git: >
      repo=https://github.com/majutsushi/tagbar.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/tagbar

  - name: Clone nerdcommenter from Github.
    git: >
      repo=https://github.com/scrooloose/nerdcommenter.git
      dest=/home/{{ webadmin_user }}/.vim/bundle/nerdcommenter
