---
  - include: 'gems.yml'

  - name: Setup | Install required packages.
    action: apt pkg={{ item }} state=installed update_cache=yes
    when: ansible_os_family == "Debian"
    with_items:
      - figlet
      - ctags
      - unzip
      - vim
      - git
      - curl

  - name: Add intro text
    template:  src=10-help-text.j2 dest={{ intro_path }}

  - name: My.cnf
    template: src=my.cnf.j2 dest=/home/{{ webadmin_user }}/.my.cnf

  - name: Clone Buck from GitHub.
    git: >
      repo=https://github.com/NuCivic/buck.git
      dest=/home/{{ webadmin_user }}/.drush/buck
      accept_hostkey=yes
      update=yes

  - name: Clone Drush Sync Aliases from GitHub.
    git: >
      repo=https://github.com/acouch/sync_aliases.git
      dest=/home/{{ webadmin_user }}/.drush/sync_aliases
      accept_hostkey=yes
      update=yes

  - name: Clone Drush Subtree from GitHub.
    git: >
      repo=https://github.com/WhiteHouse/drushsubtree.git
      dest=/home/{{ webadmin_user }}/.drush/drushsubtree
      accept_hostkey=yes
      update=yes
      
  - name: Clone Registry Rebuild from Drupal.
    git: >
      repo=http://git.drupal.org/project/registry_rebuild.git
      dest=/home/{{ webadmin_user }}/.drush/registry_rebuild
      accept_hostkey=yes
      version=7.x-2.x
      update=yes 

  - name: Clone Build Manager from GitHub.
    git: >
      repo=https://github.com/WhiteHouse/buildmanager.git
      dest=/home/{{ webadmin_user }}/.drush/buildmanager
      accept_hostkey=yes
      update=yes

  - name: Clone CodeSniffer from GitHub.
    git: >
      repo=https://github.com/squizlabs/PHP_CodeSniffer.git
      dest=/home/{{ webadmin_user }}/.composer/vendor/squizlabs
      update=yes

  - name: Clone Coder from Drupal.
    git: >
      repo=http://git.drupal.org/project/coder.git
      dest=/home/{{ webadmin_user }}/.drush/coder
      version=7.x-2.x
      update=yes

  - name: Clone vhost from Github.
    git: >
      repo=https://github.com/NuCivic/vhost.git
      dest=/home/{{ webadmin_user }}/.drush/vhost
      update=yes

  - name: Add Drush bash completion.
    command: cp /usr/local/share/drush/drush.complete.sh /etc/bash_completion.d/
    args:
      creates: /etc/bash_completion.d/drush.complete.sh

  - name: Gives .composer right ownership
    file: path=/home/{{ webadmin_user }}/.composer state=directory owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Gives .drush right ownership
    file: path=/home/{{ webadmin_user }}/.drush state=directory owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Creates .composer/vendor/bin
    file: path=/home/{{ webadmin_user }}/.composer/vendor/bin state=directory owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Create symlink to phpcs
    file: src=/home/{{ webadmin_user }}/.composer/vendor/squizlabs/scripts/phpcs dest=/home/{{ webadmin_user }}/.composer/vendor/bin/phpcs state=link owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Create symlink to Drupal coding standards
    file: src=/home/{{ webadmin_user }}/.drush/coder/coder_sniffer/Drupal dest=/home/{{ webadmin_user }}/.composer/vendor/squizlabs/CodeSniffer/Standards/Drupal state=link owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Add gitconfig
    template: src=gitconfig dest=/etc/gitconfig

  - name: Add gitignore
    template: src=gitignore dest=/usr/share/git-core/templates/info/exclude

  - name: Add git_attribute
    template: src=git_attribute dest=/usr/share/git-core/templates/info/attribute

  - name: Add buck_qa
    template: src=buck_qa dest=/usr/local/bin/buck_qa owner={{ webadmin_user }} group={{ webadmin_user }} mode=0755

  - name: Add runtags
    template: src=runtags dest=/usr/local/bin/runtags owner={{ webadmin_user }} group={{ webadmin_user }} mode=0755

  - name: Add random-password
    template: src=make-random-password dest=/usr/local/bin/make-random-password owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Check Terminus installed
    stat: path=/usr/local/lib/terminus-{{ terminus_version }}
    register: termins_installed

  - name: Install Terminus
    shell: curl https://github.com/pantheon-systems/cli/releases/download/{{ terminus_version }}/terminus.phar -L -o /usr/local/lib/terminus-{{ terminus_version }};
    when: not termins_installed.stat.exists

  - name: Fix Terminus permissions
    file: dest=/usr/local/bin/terminus src=/usr/local/lib/terminus-{{ terminus_version }} owner={{ webadmin_user }} group={{ webadmin_user }} mode=0755 state=link
    when: termins_installed.stat.exists

  - name: Add bashrc
    template: src=bash.bashrc dest={{ bashrc_location }}

  - name: Give {{ webadmin_user }} ownership of sites-available 
    file: path=/etc/apache2/sites-available state=directory owner={{ webadmin_user }} group={{ webadmin_user }}

  - name: Enable mod_rewrite.
    command: a2emod rewrite
